# Generated by Django 5.0 on 2023-12-28 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rental_app", "0002_review_remove_listing_description_and_more"),
        ("utils_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rental_app.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utils_app.user",
                    ),
                ),
                ("leasing_start", models.DateTimeField(auto_now_add=True)),
                ("leasing_end", models.DateTimeField()),
                (
                    "favourites",
                    models.ManyToManyField(
                        through="tenant_app.Favourite", to="rental_app.listing"
                    ),
                ),
            ],
            bases=("utils_app.user",),
        ),
        migrations.AddField(
            model_name="favourite",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenant_app.tenant"
            ),
        ),
    ]
