# Generated by Django 5.0 on 2023-12-28 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("utils_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flat",
            fields=[
                (
                    "realestate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utils_app.realestate",
                    ),
                ),
                ("bedrooms", models.IntegerField()),
                ("bathroom", models.BooleanField()),
                ("floor_number", models.IntegerField()),
            ],
            bases=("utils_app.realestate",),
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "realestate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utils_app.realestate",
                    ),
                ),
                ("bedrooms", models.IntegerField()),
                ("floors", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
            ],
            bases=("utils_app.realestate",),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "realestate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utils_app.realestate",
                    ),
                ),
                ("area", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            bases=("utils_app.realestate",),
        ),
    ]
