# Generated by Django 5.0 on 2023-12-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="listing",
            name="description",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="price",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="title",
        ),
    ]
