# Generated by Django 5.0 on 2023-12-28 22:51

import django.db.models.deletion
import rental_app.models
import utils_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landlord_app", "0001_initial"),
        ("rental_app", "0002_review_remove_listing_description_and_more"),
        ("tenant_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="cur_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant_app.tenant",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="landlord",
            field=models.ForeignKey(
                default=rental_app.models.default_landlord,
                on_delete=django.db.models.deletion.CASCADE,
                to="landlord_app.landlord",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "HOUSE"),
                    ("flat", "FLAT"),
                    ("warehouse", "WAREHOUSE"),
                ],
                default=utils_app.models.RealEstate,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rental_app.listing"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenant_app.tenant"
            ),
        ),
    ]
