# Generated by Django 5.0 on 2023-12-28 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landlord_app", "0001_initial"),
        ("rental_app", "0003_listing_cur_tenant_listing_landlord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="landlord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="landlord_app.landlord"
            ),
        ),
    ]
