# Generated by Django 5.0 on 2023-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
    ]
