# Generated by Django 5.0 on 2023-12-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils_app", "0002_alter_realestate_rating_alter_user_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0.0, max_digits=2, null=True
            ),
        ),
    ]
